name: Lint GitHub Actions workflows
on:
  pull_request:
    paths:
      - '.github/**'

jobs:
  actionlint:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      # see https://github.com/rhysd/actionlint/blob/main/docs/usage.md
      - name: Check workflow files
        # https://hub.docker.com/r/rhysd/actionlint/tags
        uses: docker://rhysd/actionlint:1.7.0
